### PR TITLE
Fire metric upon completion of a message set

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@gsvr review please

**Comment by gsvr** [comment]
@imsickofmaps From the issue title I'd have thought the metric we need to fire is upon completion of each message set, not all subsequent message sets - is the title inaccurate?

**Comment by imsickofmaps** [comment]
@gsvr sorry - maybe better titled with an extra s "Fire metric upon completion of a message sets" - i.e. when all sets exhausted.

**Comment by gsvr** [comment]
:+1: when travis happy

**Pull request merged**
